name: Docker Image CI

on:
  push:
    branches: ["main"]        # build & push on direct commits/merges
  pull_request:
    branches: ["main"]        # build only (no push)

# allow the job to write to GHCR
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - uses: actions/checkout@v4

      # 2. (Optional) produce useful tags/labels like :latest, :sha
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      # 3. Set up Buildx
      - uses: docker/setup-buildx-action@v3

      # 4. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Build—and push only on push events
      - name: Build & (conditionally) push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max
